version: '3.8'

services:
  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password #--init-file /data/application/init.sql
    container_name: MYSQL-API-BACKEND
    env_file:
      - ./.env
    ports:
      - "3366:3306"
    volumes:
      - data:/var/lib/mysql
      - ./mysql/data/conf.d:/etc/mysql/conf.d
      # - ./mysql/data/init.sql:/data/application/init.sql

  ifoverflow:
    container_name: ifoverflow
    build: .
    ports:
      - "8088:8000"
    volumes:
      - .:/opt/code
    depends_on:
      - db

volumes:
  data:
